[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
nft_stacking = "8MSZo9zf8Y4MVaSf6Mu4qJg9pCeWVgtquLTU7S9ud29"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
